import bcrypt from 'bcryptjs';
import { pool } from '../src/config/database';

async function seed() {
  console.log('Sembrando datos iniciales...\n');

  // ── Usuarios ──
  const adminPass = await bcrypt.hash('admin123', 12);
  const comercialPass = await bcrypt.hash('comercial123', 12);
  const supervisorPass = await bcrypt.hash('supervisor123', 12);

  await pool.query(`
    INSERT INTO users (email, password, nombre, apellidos, telefono, role)
    VALUES
      ('admin@sinergia.es', $1, 'Carlos', 'Martinez Lopez', '600111222', 'admin'),
      ('juan@sinergia.es', $2, 'Juan', 'Garcia Fernandez', '600333444', 'comercial'),
      ('maria@sinergia.es', $3, 'Maria', 'Rodriguez Sanchez', '600555666', 'comercial'),
      ('pedro@sinergia.es', $4, 'Pedro', 'Lopez Ruiz', '600777888', 'supervisor')
    ON CONFLICT (email) DO NOTHING
  `, [adminPass, comercialPass, comercialPass, supervisorPass]);

  console.log('Usuarios creados.');

  // Obtener IDs de usuarios
  const usersResult = await pool.query("SELECT id, email FROM users");
  const users: Record<string, string> = {};
  usersResult.rows.forEach((u: any) => { users[u.email] = u.id; });

  const juanId = users['juan@sinergia.es'];
  const mariaId = users['maria@sinergia.es'];

  // ── Zonas ──
  await pool.query(`
    INSERT INTO zones (nombre, descripcion, color) VALUES
      ('Centro Madrid', 'Zona centro de Madrid capital', '#ef4444'),
      ('Norte Madrid', 'Zona norte: Chamartin, Tetuan, Fuencarral', '#3b82f6'),
      ('Sur Madrid', 'Zona sur: Getafe, Leganes, Alcorcon', '#10b981'),
      ('Este Madrid', 'Zona este: Alcala, Torrejon, Coslada', '#f59e0b'),
      ('Malaga Centro', 'Centro historico y alrededores', '#8b5cf6'),
      ('Costa del Sol', 'Fuengirola, Marbella, Estepona', '#ec4899')
    ON CONFLICT DO NOTHING
  `);

  console.log('Zonas creadas.');

  // Obtener IDs de zonas
  const zonesResult = await pool.query("SELECT id, nombre FROM zones");
  const zones: Record<string, string> = {};
  zonesResult.rows.forEach((z: any) => { zones[z.nombre] = z.id; });

  // ── 20 Prospectos realistas ──
  const prospects = [
    {
      nombre_negocio: 'Bar El Rincon de Pepe',
      nombre_contacto: 'Jose Manuel Gutierrez',
      categoria: 'bar',
      telefono_movil: '612345678',
      email_principal: 'pepebar@gmail.com',
      direccion_completa: 'Calle Gran Via 45, Local 2',
      codigo_postal: '28013',
      municipio: 'Madrid',
      provincia: 'Madrid',
      coordenadas_lat: 40.4200,
      coordenadas_lng: -3.7025,
      comercializadora_actual: 'Iberdrola',
      tarifa_actual: '3.0TD',
      potencia_p1_kw: 15,
      potencia_p2_kw: 15,
      consumo_anual_kwh: 28000,
      gasto_mensual_estimado_eur: 380,
      estado: 'interesado',
      prioridad: 'alta',
      temperatura: 'caliente',
      zona_id: zones['Centro Madrid'],
      asignado_a: juanId,
      fuente: 'manual',
      notas_internas: 'Dueño muy interesado, quiere ver oferta esta semana. Contrato con Iberdrola vence en 2 meses.',
    },
    {
      nombre_negocio: 'Restaurante La Taberna Andaluza',
      nombre_contacto: 'Ana Maria Flores',
      categoria: 'restaurante',
      telefono_movil: '634567890',
      email_principal: 'lataberna@hotmail.com',
      direccion_completa: 'Calle Fuencarral 88',
      codigo_postal: '28004',
      municipio: 'Madrid',
      provincia: 'Madrid',
      coordenadas_lat: 40.4268,
      coordenadas_lng: -3.7012,
      comercializadora_actual: 'Endesa',
      tarifa_actual: '3.0TD',
      potencia_p1_kw: 25,
      potencia_p2_kw: 25,
      consumo_anual_kwh: 45000,
      gasto_mensual_estimado_eur: 620,
      estado: 'oferta_enviada',
      prioridad: 'alta',
      temperatura: 'caliente',
      zona_id: zones['Centro Madrid'],
      asignado_a: juanId,
      fuente: 'manual',
      notas_internas: 'Oferta enviada el lunes. Ana pidio revisar con su socio antes de firmar.',
    },
    {
      nombre_negocio: 'Taller Mecanico Hermanos Lopez',
      nombre_contacto: 'Francisco Lopez',
      categoria: 'taller',
      telefono_movil: '656789012',
      email_principal: 'tallerlopez@gmail.com',
      direccion_completa: 'Avda de la Constitucion 12',
      codigo_postal: '28901',
      municipio: 'Getafe',
      provincia: 'Madrid',
      coordenadas_lat: 40.3050,
      coordenadas_lng: -3.7327,
      comercializadora_actual: 'Naturgy',
      tarifa_actual: '3.1TD',
      potencia_p1_kw: 35,
      potencia_p2_kw: 35,
      potencia_p3_kw: 35,
      consumo_anual_kwh: 65000,
      gasto_mensual_estimado_eur: 890,
      estado: 'contactado',
      prioridad: 'media',
      temperatura: 'tibio',
      zona_id: zones['Sur Madrid'],
      asignado_a: juanId,
      fuente: 'manual',
      notas_internas: 'Francisco tiene contrato hasta diciembre. Interesado pero no urgente.',
    },
    {
      nombre_negocio: 'Peluqueria Glamour',
      nombre_contacto: 'Lucia Sanchez',
      categoria: 'peluqueria',
      telefono_movil: '678901234',
      email_principal: 'glamourpelu@gmail.com',
      direccion_completa: 'Calle Mayor 22',
      codigo_postal: '28801',
      municipio: 'Alcala de Henares',
      provincia: 'Madrid',
      coordenadas_lat: 40.4818,
      coordenadas_lng: -3.3635,
      comercializadora_actual: 'Repsol',
      tarifa_actual: '2.0TD',
      potencia_p1_kw: 8,
      consumo_anual_kwh: 12000,
      gasto_mensual_estimado_eur: 165,
      estado: 'pendiente',
      prioridad: 'baja',
      temperatura: 'frio',
      zona_id: zones['Este Madrid'],
      asignado_a: mariaId,
      fuente: 'csv_importado',
    },
    {
      nombre_negocio: 'Hotel Costa del Sol',
      nombre_contacto: 'Roberto Jimenez',
      categoria: 'hotel',
      telefono_movil: '690123456',
      email_principal: 'direccion@hotelcostasol.es',
      web: 'www.hotelcostasol.es',
      direccion_completa: 'Paseo Maritimo 156',
      codigo_postal: '29640',
      municipio: 'Fuengirola',
      provincia: 'Malaga',
      coordenadas_lat: 36.5440,
      coordenadas_lng: -4.6248,
      comercializadora_actual: 'Endesa',
      tarifa_actual: '6.1TD',
      potencia_p1_kw: 150,
      potencia_p2_kw: 150,
      potencia_p3_kw: 100,
      consumo_anual_kwh: 320000,
      gasto_mensual_estimado_eur: 4200,
      estado: 'negociacion',
      prioridad: 'alta',
      temperatura: 'caliente',
      zona_id: zones['Costa del Sol'],
      asignado_a: mariaId,
      fuente: 'referido',
      notas_internas: 'Gran cuenta. Roberto es el director general. Quiere 15% de descuento minimo.',
    },
    {
      nombre_negocio: 'Supermercado La Plaza',
      nombre_contacto: 'Miguel Angel Torres',
      categoria: 'supermercado',
      telefono_movil: '612098765',
      email_principal: 'matorres@laplaza.es',
      direccion_completa: 'Calle Real 5',
      codigo_postal: '28911',
      municipio: 'Leganes',
      provincia: 'Madrid',
      coordenadas_lat: 40.3270,
      coordenadas_lng: -3.7643,
      comercializadora_actual: 'Iberdrola',
      tarifa_actual: '3.0TD',
      potencia_p1_kw: 45,
      potencia_p2_kw: 45,
      consumo_anual_kwh: 85000,
      gasto_mensual_estimado_eur: 1150,
      estado: 'contrato_firmado',
      prioridad: 'alta',
      temperatura: 'caliente',
      zona_id: zones['Sur Madrid'],
      asignado_a: juanId,
      fuente: 'manual',
      ahorro_estimado_eur: 1800,
      ahorro_porcentaje: 13,
      notas_internas: 'Contrato firmado. Ahorro de 1800 EUR/año. Miguel muy contento.',
    },
    {
      nombre_negocio: 'Farmacia Central',
      nombre_contacto: 'Carmen Ruiz',
      categoria: 'farmacia',
      telefono_movil: '634098765',
      email_principal: 'farmaciacentral@gmail.com',
      direccion_completa: 'Plaza de Espana 3',
      codigo_postal: '28008',
      municipio: 'Madrid',
      provincia: 'Madrid',
      coordenadas_lat: 40.4231,
      coordenadas_lng: -3.7125,
      comercializadora_actual: 'Endesa',
      tarifa_actual: '2.0TD',
      potencia_p1_kw: 10,
      consumo_anual_kwh: 18000,
      gasto_mensual_estimado_eur: 245,
      estado: 'volver_llamar',
      prioridad: 'media',
      temperatura: 'tibio',
      zona_id: zones['Centro Madrid'],
      asignado_a: juanId,
      fuente: 'manual',
      notas_internas: 'Carmen pidio que la llame el proximo lunes por la tarde.',
    },
    {
      nombre_negocio: 'Clinica Dental Sonrisa',
      nombre_contacto: 'Dr. Alvaro Mendez',
      categoria: 'dental',
      telefono_movil: '656098765',
      email_principal: 'info@clinicasonrisa.es',
      web: 'www.clinicasonrisa.es',
      direccion_completa: 'Calle Velazquez 78, 1o D',
      codigo_postal: '28006',
      municipio: 'Madrid',
      provincia: 'Madrid',
      coordenadas_lat: 40.4310,
      coordenadas_lng: -3.6834,
      comercializadora_actual: 'Naturgy',
      tarifa_actual: '3.0TD',
      potencia_p1_kw: 20,
      potencia_p2_kw: 20,
      consumo_anual_kwh: 35000,
      gasto_mensual_estimado_eur: 480,
      estado: 'llamado',
      prioridad: 'media',
      temperatura: 'frio',
      zona_id: zones['Centro Madrid'],
      asignado_a: mariaId,
      fuente: 'google_places',
      rating_google: 4.5,
      num_reviews_google: 127,
      notas_internas: 'Llamado 2 veces, no contesta. Intentar por email.',
    },
    {
      nombre_negocio: 'Gimnasio FitZone',
      nombre_contacto: 'David Moreno',
      categoria: 'gym',
      telefono_movil: '678098765',
      email_principal: 'david@fitzone.es',
      web: 'www.fitzone.es',
      direccion_completa: 'Avda de America 45',
      codigo_postal: '28028',
      municipio: 'Madrid',
      provincia: 'Madrid',
      coordenadas_lat: 40.4380,
      coordenadas_lng: -3.6685,
      comercializadora_actual: 'Iberdrola',
      tarifa_actual: '3.1TD',
      potencia_p1_kw: 60,
      potencia_p2_kw: 60,
      potencia_p3_kw: 40,
      consumo_anual_kwh: 120000,
      gasto_mensual_estimado_eur: 1650,
      estado: 'interesado',
      prioridad: 'alta',
      temperatura: 'caliente',
      zona_id: zones['Norte Madrid'],
      asignado_a: mariaId,
      fuente: 'manual',
      notas_internas: 'David quiere reducir factura. Tiene 3 locales, posible gran cuenta.',
    },
    {
      nombre_negocio: 'Panaderia El Horno de Oro',
      nombre_contacto: 'Maria Jose Navarro',
      categoria: 'panaderia',
      telefono_movil: '690098765',
      email_principal: 'hornodeoro@gmail.com',
      direccion_completa: 'Calle Alcala 234',
      codigo_postal: '28027',
      municipio: 'Madrid',
      provincia: 'Madrid',
      coordenadas_lat: 40.4350,
      coordenadas_lng: -3.6540,
      comercializadora_actual: 'Repsol',
      tarifa_actual: '3.0TD',
      potencia_p1_kw: 30,
      potencia_p2_kw: 30,
      consumo_anual_kwh: 52000,
      gasto_mensual_estimado_eur: 710,
      estado: 'pendiente',
      prioridad: 'media',
      temperatura: 'frio',
      zona_id: zones['Norte Madrid'],
      asignado_a: juanId,
      fuente: 'csv_importado',
    },
    {
      nombre_negocio: 'Ferreteria Martinez',
      nombre_contacto: 'Antonio Martinez',
      categoria: 'ferreteria',
      telefono_movil: '612987654',
      email_principal: 'ferremartinez@hotmail.com',
      direccion_completa: 'Calle Toledo 67',
      codigo_postal: '28005',
      municipio: 'Madrid',
      provincia: 'Madrid',
      coordenadas_lat: 40.4095,
      coordenadas_lng: -3.7080,
      comercializadora_actual: 'Endesa',
      tarifa_actual: '2.0TD',
      potencia_p1_kw: 12,
      consumo_anual_kwh: 15000,
      gasto_mensual_estimado_eur: 205,
      estado: 'rechazado',
      prioridad: 'baja',
      temperatura: 'frio',
      zona_id: zones['Centro Madrid'],
      asignado_a: juanId,
      fuente: 'manual',
      notas_internas: 'No quiere cambiar. Dice que esta contento con Endesa. Revisar en 6 meses.',
    },
    {
      nombre_negocio: 'Cafeteria Milano',
      nombre_contacto: 'Isabella Rossi',
      categoria: 'cafeteria',
      telefono_movil: '634987654',
      email_principal: 'cafemilano@gmail.com',
      instagram: '@cafeteriamilano',
      direccion_completa: 'Paseo de la Castellana 120',
      codigo_postal: '28046',
      municipio: 'Madrid',
      provincia: 'Madrid',
      coordenadas_lat: 40.4570,
      coordenadas_lng: -3.6910,
      comercializadora_actual: 'Naturgy',
      tarifa_actual: '2.0TD',
      potencia_p1_kw: 10,
      consumo_anual_kwh: 16000,
      gasto_mensual_estimado_eur: 220,
      estado: 'contactado',
      prioridad: 'media',
      temperatura: 'tibio',
      zona_id: zones['Norte Madrid'],
      asignado_a: mariaId,
      fuente: 'google_places',
      rating_google: 4.3,
      num_reviews_google: 89,
    },
    {
      nombre_negocio: 'Lavanderia Express Clean',
      nombre_contacto: 'Luis Fernandez',
      categoria: 'lavanderia',
      telefono_movil: '656987654',
      email_principal: 'expressclean@gmail.com',
      direccion_completa: 'Calle Bravo Murillo 180',
      codigo_postal: '28020',
      municipio: 'Madrid',
      provincia: 'Madrid',
      coordenadas_lat: 40.4560,
      coordenadas_lng: -3.6990,
      comercializadora_actual: 'Iberdrola',
      tarifa_actual: '3.0TD',
      potencia_p1_kw: 40,
      potencia_p2_kw: 40,
      consumo_anual_kwh: 75000,
      gasto_mensual_estimado_eur: 1020,
      estado: 'interesado',
      prioridad: 'alta',
      temperatura: 'tibio',
      zona_id: zones['Norte Madrid'],
      asignado_a: juanId,
      fuente: 'manual',
      notas_internas: 'Alto consumo por las maquinas. Buen potencial de ahorro.',
    },
    {
      nombre_negocio: 'Boutique Moda Carmen',
      nombre_contacto: 'Carmen Delgado',
      categoria: 'tienda_ropa',
      telefono_movil: '678987654',
      email_principal: 'modacarmen@outlook.es',
      instagram: '@modacarmen_boutique',
      direccion_completa: 'Calle Serrano 45',
      codigo_postal: '28001',
      municipio: 'Madrid',
      provincia: 'Madrid',
      coordenadas_lat: 40.4280,
      coordenadas_lng: -3.6850,
      comercializadora_actual: 'Endesa',
      tarifa_actual: '2.0TD',
      potencia_p1_kw: 6,
      consumo_anual_kwh: 8000,
      gasto_mensual_estimado_eur: 110,
      estado: 'pendiente',
      prioridad: 'baja',
      temperatura: 'frio',
      zona_id: zones['Centro Madrid'],
      asignado_a: mariaId,
      fuente: 'csv_importado',
    },
    {
      nombre_negocio: 'Taller de Coches Premium Auto',
      nombre_contacto: 'Alejandro Vega',
      categoria: 'taller',
      telefono_movil: '690987654',
      email_principal: 'info@premiumauto.es',
      web: 'www.premiumauto.es',
      direccion_completa: 'Poligono Industrial San Fernando, Nave 12',
      codigo_postal: '28850',
      municipio: 'Torrejon de Ardoz',
      provincia: 'Madrid',
      coordenadas_lat: 40.4553,
      coordenadas_lng: -3.4700,
      comercializadora_actual: 'Naturgy',
      tarifa_actual: '3.1TD',
      potencia_p1_kw: 50,
      potencia_p2_kw: 50,
      potencia_p3_kw: 30,
      consumo_anual_kwh: 95000,
      gasto_mensual_estimado_eur: 1300,
      estado: 'oferta_enviada',
      prioridad: 'alta',
      temperatura: 'caliente',
      zona_id: zones['Este Madrid'],
      asignado_a: juanId,
      fuente: 'referido',
      notas_internas: 'Referido por Miguel del Supermercado La Plaza. Oferta enviada ayer.',
    },
    {
      nombre_negocio: 'Restaurante Marisqueria El Puerto',
      nombre_contacto: 'Fernando Campos',
      categoria: 'restaurante',
      telefono_movil: '612876543',
      email_principal: 'elpuerto@restaurante.es',
      web: 'www.marisqueriaelpuerto.es',
      direccion_completa: 'Calle Larios 15',
      codigo_postal: '29015',
      municipio: 'Malaga',
      provincia: 'Malaga',
      coordenadas_lat: 36.7197,
      coordenadas_lng: -4.4200,
      comercializadora_actual: 'Endesa',
      tarifa_actual: '3.0TD',
      potencia_p1_kw: 35,
      potencia_p2_kw: 35,
      consumo_anual_kwh: 58000,
      gasto_mensual_estimado_eur: 790,
      estado: 'llamado',
      prioridad: 'media',
      temperatura: 'frio',
      zona_id: zones['Malaga Centro'],
      asignado_a: mariaId,
      fuente: 'google_places',
      rating_google: 4.7,
      num_reviews_google: 312,
    },
    {
      nombre_negocio: 'Oficina Seguros Mapfre - Delegacion Sur',
      nombre_contacto: 'Patricia Morales',
      categoria: 'oficina',
      telefono_movil: '634876543',
      email_principal: 'pmorales@agente.mapfre.es',
      direccion_completa: 'Avda de Andalucia 8, 2o',
      codigo_postal: '29007',
      municipio: 'Malaga',
      provincia: 'Malaga',
      coordenadas_lat: 36.7150,
      coordenadas_lng: -4.4300,
      comercializadora_actual: 'Iberdrola',
      tarifa_actual: '2.0TD',
      potencia_p1_kw: 10,
      consumo_anual_kwh: 14000,
      gasto_mensual_estimado_eur: 190,
      estado: 'perdido',
      prioridad: 'baja',
      temperatura: 'frio',
      zona_id: zones['Malaga Centro'],
      asignado_a: mariaId,
      fuente: 'manual',
      notas_internas: 'Patricia dice que la decision la toma central. No puede cambiar proveedor.',
    },
    {
      nombre_negocio: 'Chiringuito Playa Bella',
      nombre_contacto: 'Raul Ortega',
      categoria: 'bar',
      telefono_movil: '656876543',
      email_principal: 'playabella@gmail.com',
      direccion_completa: 'Paseo Maritimo 45',
      codigo_postal: '29602',
      municipio: 'Marbella',
      provincia: 'Malaga',
      coordenadas_lat: 36.5100,
      coordenadas_lng: -4.8850,
      comercializadora_actual: 'Endesa',
      tarifa_actual: '3.0TD',
      potencia_p1_kw: 20,
      potencia_p2_kw: 20,
      consumo_anual_kwh: 38000,
      gasto_mensual_estimado_eur: 520,
      estado: 'contactado',
      prioridad: 'media',
      temperatura: 'tibio',
      zona_id: zones['Costa del Sol'],
      asignado_a: mariaId,
      fuente: 'manual',
      notas_internas: 'Solo abre en temporada alta (mayo-octubre). Contactar en abril.',
    },
    {
      nombre_negocio: 'Centro Veterinario Huellitas',
      nombre_contacto: 'Dra. Elena Castro',
      categoria: 'otro',
      subcategoria: 'veterinaria',
      telefono_movil: '678876543',
      email_principal: 'huellitas@veterinaria.es',
      web: 'www.veterinariahuellitas.es',
      direccion_completa: 'Calle Goya 110',
      codigo_postal: '28009',
      municipio: 'Madrid',
      provincia: 'Madrid',
      coordenadas_lat: 40.4250,
      coordenadas_lng: -3.6750,
      comercializadora_actual: 'Repsol',
      tarifa_actual: '3.0TD',
      potencia_p1_kw: 18,
      potencia_p2_kw: 18,
      consumo_anual_kwh: 30000,
      gasto_mensual_estimado_eur: 410,
      estado: 'interesado',
      prioridad: 'media',
      temperatura: 'tibio',
      zona_id: zones['Centro Madrid'],
      asignado_a: juanId,
      fuente: 'google_places',
      rating_google: 4.8,
      num_reviews_google: 245,
      notas_internas: 'Elena interesada. Pide presupuesto por email antes de reunirse.',
    },
    {
      nombre_negocio: 'Autolavado Splash',
      nombre_contacto: 'Jorge Navarro',
      categoria: 'otro',
      subcategoria: 'autolavado',
      telefono_movil: '690876543',
      email_principal: 'splash.autolavado@gmail.com',
      direccion_completa: 'Carretera de Toledo km 8',
      codigo_postal: '28921',
      municipio: 'Alcorcon',
      provincia: 'Madrid',
      coordenadas_lat: 40.3450,
      coordenadas_lng: -3.8250,
      comercializadora_actual: 'Naturgy',
      tarifa_actual: '3.1TD',
      potencia_p1_kw: 55,
      potencia_p2_kw: 55,
      potencia_p3_kw: 35,
      consumo_anual_kwh: 110000,
      gasto_mensual_estimado_eur: 1500,
      estado: 'contrato_firmado',
      prioridad: 'alta',
      temperatura: 'caliente',
      zona_id: zones['Sur Madrid'],
      asignado_a: juanId,
      fuente: 'referido',
      ahorro_estimado_eur: 2400,
      ahorro_porcentaje: 13.3,
      notas_internas: 'Contrato firmado. Gran ahorro por alto consumo. Jorge encantado.',
    },
  ];

  // Insertar prospectos
  for (const p of prospects) {
    const fields = Object.keys(p);
    const values = Object.values(p);
    const placeholders = fields.map((_, i) => `$${i + 1}`);

    await pool.query(
      `INSERT INTO prospects (${fields.join(', ')}) VALUES (${placeholders.join(', ')})
       ON CONFLICT DO NOTHING`,
      values
    );
  }

  console.log(`${prospects.length} prospectos creados.`);

  // Obtener IDs de prospectos
  const prospectsResult = await pool.query("SELECT id, nombre_negocio FROM prospects");
  const prospectIds: Record<string, string> = {};
  prospectsResult.rows.forEach((p: any) => { prospectIds[p.nombre_negocio] = p.id; });

  const adminId = users['admin@sinergia.es'];

  // ── Historial de contactos ──
  const contactHistory = [
    // Bar El Rincon de Pepe - varias interacciones
    { prospect_id: prospectIds['Bar El Rincon de Pepe'], user_id: juanId, tipo: 'llamada', resultado: 'positivo', nota: 'Hable con Jose Manuel. Muy interesado en cambiar de comercializadora. Pide que le envie oferta.', duracion_minutos: 8, estado_anterior: 'pendiente', estado_nuevo: 'contactado' },
    { prospect_id: prospectIds['Bar El Rincon de Pepe'], user_id: juanId, tipo: 'whatsapp', resultado: 'positivo', nota: 'Le envie info por WhatsApp. Confirmo que quiere reunion presencial.', estado_anterior: 'contactado', estado_nuevo: 'interesado' },
    { prospect_id: prospectIds['Bar El Rincon de Pepe'], user_id: juanId, tipo: 'visita_presencial', resultado: 'positivo', nota: 'Visita al bar. Revisamos factura actual. Margen de ahorro del 12%. Jose Manuel quiere ver oferta formal.', duracion_minutos: 35, proxima_accion: 'Enviar oferta formal', fecha_proxima_accion: '2026-04-07T10:00' },

    // Restaurante La Taberna Andaluza
    { prospect_id: prospectIds['Restaurante La Taberna Andaluza'], user_id: juanId, tipo: 'llamada', resultado: 'positivo', nota: 'Primera llamada. Ana Maria atiende. Interesada pero ocupada, pide llamar manana.', duracion_minutos: 4 },
    { prospect_id: prospectIds['Restaurante La Taberna Andaluza'], user_id: juanId, tipo: 'llamada', resultado: 'positivo', nota: 'Segunda llamada. Revisamos datos de consumo. Quiere oferta por email.', duracion_minutos: 12, estado_anterior: 'llamado', estado_nuevo: 'interesado' },
    { prospect_id: prospectIds['Restaurante La Taberna Andaluza'], user_id: juanId, tipo: 'oferta_enviada', resultado: 'positivo', nota: 'Oferta enviada por email. Ahorro estimado 15%. Pendiente de respuesta.', estado_anterior: 'interesado', estado_nuevo: 'oferta_enviada' },

    // Taller Mecanico
    { prospect_id: prospectIds['Taller Mecanico Hermanos Lopez'], user_id: juanId, tipo: 'llamada', resultado: 'no_contesto', nota: 'No contesta. Intentar mas tarde.', duracion_minutos: 0 },
    { prospect_id: prospectIds['Taller Mecanico Hermanos Lopez'], user_id: juanId, tipo: 'llamada', resultado: 'positivo', nota: 'Francisco contesto. Tiene contrato hasta diciembre, no urgente pero escucha propuesta.', duracion_minutos: 6, estado_anterior: 'pendiente', estado_nuevo: 'contactado' },

    // Clinica Dental
    { prospect_id: prospectIds['Clinica Dental Sonrisa'], user_id: mariaId, tipo: 'llamada', resultado: 'no_contesto', nota: 'No contesta, suena ocupado.', duracion_minutos: 0 },
    { prospect_id: prospectIds['Clinica Dental Sonrisa'], user_id: mariaId, tipo: 'llamada', resultado: 'buzon', nota: 'Buzon de voz. Dejo mensaje.', duracion_minutos: 0, estado_anterior: 'pendiente', estado_nuevo: 'llamado' },
    { prospect_id: prospectIds['Clinica Dental Sonrisa'], user_id: mariaId, tipo: 'email_enviado', resultado: 'neutro', nota: 'Email enviado con info de Somos Sinergia y datos de contacto.' },

    // Gimnasio FitZone
    { prospect_id: prospectIds['Gimnasio FitZone'], user_id: mariaId, tipo: 'llamada', resultado: 'positivo', nota: 'David muy receptivo. Tiene 3 locales, el consumo total es enorme. Gran oportunidad.', duracion_minutos: 15, estado_anterior: 'pendiente', estado_nuevo: 'interesado' },
    { prospect_id: prospectIds['Gimnasio FitZone'], user_id: mariaId, tipo: 'nota_interna', resultado: 'neutro', nota: 'Consultar con direccion si podemos hacer oferta multi-local con descuento adicional.' },

    // Hotel Costa del Sol
    { prospect_id: prospectIds['Hotel Costa del Sol'], user_id: mariaId, tipo: 'llamada', resultado: 'positivo', nota: 'Roberto interesado. Pide reunirse en persona la proxima semana.', duracion_minutos: 10, estado_anterior: 'pendiente', estado_nuevo: 'contactado' },
    { prospect_id: prospectIds['Hotel Costa del Sol'], user_id: mariaId, tipo: 'visita_presencial', resultado: 'positivo', nota: 'Reunion en el hotel. Revisamos facturas del ultimo ano. Consumo estacional alto en verano. Roberto pide minimo 15% descuento.', duracion_minutos: 60, estado_anterior: 'contactado', estado_nuevo: 'interesado' },
    { prospect_id: prospectIds['Hotel Costa del Sol'], user_id: mariaId, tipo: 'oferta_enviada', resultado: 'positivo', nota: 'Oferta enviada con 16% ahorro. Roberto la esta revisando con el consejo.', estado_anterior: 'interesado', estado_nuevo: 'oferta_enviada' },
    { prospect_id: prospectIds['Hotel Costa del Sol'], user_id: mariaId, tipo: 'llamada', resultado: 'positivo', nota: 'Roberto confirma que el consejo lo esta evaluando. Dice que pinta bien.', duracion_minutos: 5, estado_anterior: 'oferta_enviada', estado_nuevo: 'negociacion', proxima_accion: 'Llamar en 1 semana', fecha_proxima_accion: '2026-04-11T11:00' },

    // Supermercado La Plaza (contrato firmado)
    { prospect_id: prospectIds['Supermercado La Plaza'], user_id: juanId, tipo: 'llamada', resultado: 'positivo', nota: 'Miguel interesadisimo desde el primer momento.', duracion_minutos: 8 },
    { prospect_id: prospectIds['Supermercado La Plaza'], user_id: juanId, tipo: 'visita_presencial', resultado: 'positivo', nota: 'Visita al supermercado. Revisamos cuadro electrico y facturas.', duracion_minutos: 45 },
    { prospect_id: prospectIds['Supermercado La Plaza'], user_id: juanId, tipo: 'oferta_enviada', resultado: 'positivo', nota: 'Oferta enviada. 13% ahorro, 1800 EUR/ano.' },
    { prospect_id: prospectIds['Supermercado La Plaza'], user_id: juanId, tipo: 'contrato', resultado: 'positivo', nota: 'Contrato firmado! Miguel muy contento con el ahorro.', estado_anterior: 'oferta_enviada', estado_nuevo: 'contrato_firmado' },
  ];

  for (const c of contactHistory) {
    await pool.query(
      `INSERT INTO contact_history (prospect_id, user_id, tipo, resultado, nota, duracion_minutos, estado_anterior, estado_nuevo, proxima_accion, fecha_proxima_accion)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
       ON CONFLICT DO NOTHING`,
      [c.prospect_id, c.user_id, c.tipo, c.resultado, c.nota, c.duracion_minutos || null, c.estado_anterior || null, c.estado_nuevo || null, c.proxima_accion || null, c.fecha_proxima_accion || null]
    );
  }

  console.log(`${contactHistory.length} entradas de historial de contacto creadas.`);

  // ── Visitas programadas ──
  const visits = [
    {
      prospect_id: prospectIds['Bar El Rincon de Pepe'],
      user_id: juanId,
      titulo: 'Entregar oferta - Bar El Rincon de Pepe',
      descripcion: 'Llevar oferta impresa y revisar condiciones con Jose Manuel.',
      fecha_inicio: '2026-04-07T10:00:00',
      fecha_fin: '2026-04-07T11:00:00',
      duracion_minutos: 60,
      estado: 'programada',
      direccion: 'Calle Gran Via 45, Local 2, Madrid',
      color: '#3B82F6',
    },
    {
      prospect_id: prospectIds['Gimnasio FitZone'],
      user_id: mariaId,
      titulo: 'Reunion FitZone - propuesta multi-local',
      descripcion: 'Presentar oferta para los 3 locales de David.',
      fecha_inicio: '2026-04-08T16:00:00',
      fecha_fin: '2026-04-08T17:30:00',
      duracion_minutos: 90,
      estado: 'programada',
      direccion: 'Avda de America 45, Madrid',
      color: '#10B981',
    },
    {
      prospect_id: prospectIds['Lavanderia Express Clean'],
      user_id: juanId,
      titulo: 'Visita Lavanderia Express Clean',
      descripcion: 'Ver instalaciones y maquinaria para calcular ahorro.',
      fecha_inicio: '2026-04-09T09:30:00',
      fecha_fin: '2026-04-09T10:30:00',
      duracion_minutos: 60,
      estado: 'programada',
      direccion: 'Calle Bravo Murillo 180, Madrid',
      color: '#F59E0B',
    },
    {
      prospect_id: prospectIds['Centro Veterinario Huellitas'],
      user_id: juanId,
      titulo: 'Primera visita Veterinaria Huellitas',
      descripcion: 'Elena pidio presupuesto. Llevar calculadora de ahorro.',
      fecha_inicio: '2026-04-10T11:00:00',
      fecha_fin: '2026-04-10T12:00:00',
      duracion_minutos: 60,
      estado: 'programada',
      direccion: 'Calle Goya 110, Madrid',
      color: '#8B5CF6',
    },
    {
      prospect_id: prospectIds['Hotel Costa del Sol'],
      user_id: mariaId,
      titulo: 'Seguimiento Hotel Costa del Sol',
      descripcion: 'Reunion con Roberto para cerrar negociacion.',
      fecha_inicio: '2026-04-11T10:00:00',
      fecha_fin: '2026-04-11T11:30:00',
      duracion_minutos: 90,
      estado: 'programada',
      direccion: 'Paseo Maritimo 156, Fuengirola',
      color: '#EC4899',
    },
  ];

  for (const v of visits) {
    await pool.query(
      `INSERT INTO visits (prospect_id, user_id, titulo, descripcion, fecha_inicio, fecha_fin, duracion_minutos, estado, direccion, color)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
       ON CONFLICT DO NOTHING`,
      [v.prospect_id, v.user_id, v.titulo, v.descripcion, v.fecha_inicio, v.fecha_fin, v.duracion_minutos, v.estado, v.direccion, v.color]
    );
  }

  console.log(`${visits.length} visitas programadas creadas.`);

  console.log('\nSeed completado.');

  await pool.end();
}

seed().catch((err) => {
  console.error('Error en seed:', err);
  process.exit(1);
});
